name: Build multi-platform images

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build multi-platform images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/arm64/v8
            linux/s390x
            linux/amd64
          push: false
          tags: |
            user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
